ALTER TABLE `User` ADD COLUMN `deletedAt` DATETIME(3) NULL, ADD COLUMN `deletedById` VARCHAR(191) NULL;
ALTER TABLE `Team` ADD COLUMN `deletedAt` DATETIME(3) NULL, ADD COLUMN `deletedById` VARCHAR(191) NULL;
ALTER TABLE `InventoryUnit` ADD COLUMN `deletedAt` DATETIME(3) NULL, ADD COLUMN `deletedById` VARCHAR(191) NULL;
ALTER TABLE `SiteVisit` ADD COLUMN `deletedAt` DATETIME(3) NULL, ADD COLUMN `deletedById` VARCHAR(191) NULL;
ALTER TABLE `DemoBooking` ADD COLUMN `deletedAt` DATETIME(3) NULL, ADD COLUMN `deletedById` VARCHAR(191) NULL;
ALTER TABLE `Offer` ADD COLUMN `deletedAt` DATETIME(3) NULL, ADD COLUMN `deletedById` VARCHAR(191) NULL;
